project:
  type: website

website:
  title: "Клубок"
  site-url: https://albert-rapp.de
  description: "This is Albert Rapp's personal Blog."
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - text: Archive
        href: archive.qmd
      - icon: github
        href: https://github.com/dvesti
      - icon: twitter
        href: https://twitter.com/prorab
#      - icon: youtube
#        href: https://www.youtube.com/user/Alfrodo123
#      - blog.qmd
#      - icon: github
#        href: https://github.com/
#      - icon: twitter
#        href: https://twitter.com

#########################
# You can ignore this part in the first step
#      - icon: rss
#        href: blog.xml
#      - text: Ressources
#        menu:
#          - text: DataViz Portfolio
#            href: dataviz_portfolio.html
#          - text: YARDS
#            href: https://yards.albert-rapp.de/
#          - text: R Weekly
#            href: https://rweekly.org/
#          - text: R Bloggers
#            href: https://www.r-bloggers.com/
#      - text: Archive
 #       href: archive.qmd
#  google-analytics: <Insert your ID here>
  cookie-consent: true
  twitter-card:
    image: thumbnail_blog.png
    card-style: summary_large_image
#    creator: "@rappa753"
#
#filters:
#  - code-filename
#########################
#
#format:
#  html:
#    theme: cosmo
#    css: styles.css
#
#editor: visual

format:
  html:
    theme:
      light: theme.scss
      dark: theme-dark.scss
